// Generated from the authoritative Claims QA specification. Do not hand-edit without a rubric change record.

export type ClaimsQaRubricSeed = {
  itemKey: string;
  role: string;
  category: string;
  critical: boolean;
  active: boolean;
  checkText: string;
  passingStandard: string;
  whereToFind: string;
  gradingMethod: string;
};

export const CLAIMS_QA_RUBRIC_VERSION = 'v9';

export const CLAIMS_QA_RUBRIC: ClaimsQaRubricSeed[] = [
  {
    "itemKey": "FP-15",
    "role": "First Party",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Liability decision supported by the evidence in the file",
    "passingStandard": "Decision states the basis and the evidence supports it",
    "whereToFind": "Notes / Liability Assignment",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "FP-16",
    "role": "First Party",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": false,
    "checkText": "Correct comparative or contributory standard applied for the state",
    "passingStandard": "Correct standard named and applied",
    "whereToFind": "Notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "FP-17",
    "role": "First Party",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Coverage determination correct on the facts, including gig period",
    "passingStandard": "Determination matches the verified facts",
    "whereToFind": "Coverage Check / notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "FP-18",
    "role": "First Party",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Repair or total loss decision supported",
    "passingStandard": "Decision supported by the estimate and valuation",
    "whereToFind": "Notes / estimate",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "FP-19",
    "role": "First Party",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Estimate and supplement decisions supported by the photos and the scope",
    "passingStandard": "Scope position documented and consistent with the photos",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-20",
    "role": "First Party",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Reserve reasonable against known exposure",
    "passingStandard": "Within tolerance of the documented exposure",
    "whereToFind": "Reserves",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "FP-21",
    "role": "First Party",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Subrogation decision correct: pursued where recovery exists, or the reason not to is documented",
    "passingStandard": "Pursued or documented",
    "whereToFind": "Recovery fields / notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "FP-22",
    "role": "First Party",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Payment amounts supported by documentation in the file",
    "passingStandard": "Every payment traceable to a document",
    "whereToFind": "Financial / documents",
    "gradingMethod": "Rule + human"
  },
  {
    "itemKey": "FP-01",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Coverage Check completed in full, no fields left blank",
    "passingStandard": "Every field populated",
    "whereToFind": "Claim Details > Coverage Check",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-02",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Named Driver selected and correct",
    "passingStandard": "Selected and matches the member agreement",
    "whereToFind": "Claim Details > Coverage Check",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-03",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "TNC & Market Data completed in full",
    "passingStandard": "Every field populated, including gig period and platform",
    "whereToFind": "Claim Details > TNC & Market Data",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-04",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Liability Assignment fields completed and consistent with the documented position",
    "passingStandard": "Fields populated and matching the liability note",
    "whereToFind": "Claim Details > Liability Assignment",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-05",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Incident details completed, including location and address fields",
    "passingStandard": "All location and address fields populated",
    "whereToFind": "Claim Details > Incident Details",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-06",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Facts of loss recorded in the claim itself, not only in a note",
    "passingStandard": "Present in the Facts of Loss field",
    "whereToFind": "Claim Details > Facts of Loss",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "FP-07",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Mileage updated",
    "passingStandard": "Current mileage recorded",
    "whereToFind": "Vehicle exposure record",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-08",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Auto damage exposure opened for every damaged vehicle and correctly named",
    "passingStandard": "One exposure per vehicle, named with year, make, model and VIN",
    "whereToFind": "Auto Damage Exposures",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-09",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Injured person exposure opened for every reported injury",
    "passingStandard": "One exposure per injured party",
    "whereToFind": "Injured Person Exposures",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-10",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Inspection photos uploaded and attached to the correct exposure",
    "passingStandard": "Photos present on the right exposure",
    "whereToFind": "Documents / exposure record",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-11",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Documents filed to the correct claim and categorized",
    "passingStandard": "Correct claim, correct category",
    "whereToFind": "Documents tab",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-12",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": true,
    "active": false,
    "checkText": "Reserve set on every open exposure",
    "passingStandard": "No exposure left without a reserve",
    "whereToFind": "Exposure > reserves state",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-13",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Payment issued against the correct exposure and payee",
    "passingStandard": "Matches the exposure and the party paid",
    "whereToFind": "Financial tab",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-14",
    "role": "First Party",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Tags reflect current subrogation, injury, liability and TNC status",
    "passingStandard": "Tags match the file",
    "whereToFind": "Claim header tags",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-30",
    "role": "First Party",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "A reader can follow what happened and what we did from the notes alone",
    "passingStandard": "Story complete without opening other systems",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-31",
    "role": "First Party",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Facts of loss consistent across the statement, the damage and any report, with conflicts addressed",
    "passingStandard": "Conflicts named and reconciled",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-32",
    "role": "First Party",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Each substantive action noted the same day it happened",
    "passingStandard": "Note dated the day of the action",
    "whereToFind": "Note dates",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-33",
    "role": "First Party",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Current action plan and next step stated in the latest note",
    "passingStandard": "Specific next step, not a generic follow-up",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-34",
    "role": "First Party",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Liability position documented in a note, not only in a field",
    "passingStandard": "Note states the position and the basis",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-35",
    "role": "First Party",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Closing note explains why the claim closed and how it resolved",
    "passingStandard": "Reason and resolution both stated",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-36",
    "role": "First Party",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "No contradiction between the notes and the system fields",
    "passingStandard": "Fields and notes agree",
    "whereToFind": "Notes vs claim fields",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-23",
    "role": "First Party",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Member contacted within standard, with attempts documented",
    "passingStandard": "Contact or required attempts within the standard",
    "whereToFind": "Notes",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-24",
    "role": "First Party",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Claimant or other party contacted, or attempts documented",
    "passingStandard": "Contact or attempts on file",
    "whereToFind": "Notes",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-25",
    "role": "First Party",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Contact attempts show date, method and outcome",
    "passingStandard": "All three present for each attempt",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-26",
    "role": "First Party",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Callback and follow-up commitments met",
    "passingStandard": "Met on or before the time promised",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "FP-27",
    "role": "First Party",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "File moved forward at the required intervals with no unexplained gap",
    "passingStandard": "No gap exceeding the standard between substantive actions",
    "whereToFind": "Note dates",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-28",
    "role": "First Party",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": false,
    "checkText": "Correspondence used the current template, correct state and correct entity naming",
    "passingStandard": "Correct on all three",
    "whereToFind": "Documents",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "FP-29",
    "role": "First Party",
    "category": "Communication & Follow-Up",
    "critical": true,
    "active": true,
    "checkText": "Tone professional, with no admission, promise or unauthorized disclosure",
    "passingStandard": "None present",
    "whereToFind": "Notes / correspondence",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "FP-37",
    "role": "First Party",
    "category": "Whip Operations",
    "critical": false,
    "active": true,
    "checkText": "Board updated to reflect current claim status",
    "passingStandard": "Board matches the file",
    "whereToFind": "Whip board",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "FP-38",
    "role": "First Party",
    "category": "Whip Operations",
    "critical": false,
    "active": true,
    "checkText": "Slack updated where the process requires it",
    "passingStandard": "Posted where required",
    "whereToFind": "Slack",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "FP-39",
    "role": "First Party",
    "category": "Whip Operations",
    "critical": false,
    "active": true,
    "checkText": "Claim sitting in the correct queue or team for its type",
    "passingStandard": "Assignment matches the claim type",
    "whereToFind": "Claim assignment",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "FP-40",
    "role": "First Party",
    "category": "Whip Operations",
    "critical": true,
    "active": true,
    "checkText": "Escalation made where required, including legal, high-risk and policy-limit items",
    "passingStandard": "Escalated within the business day",
    "whereToFind": "Notes / routing record",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "FP-41",
    "role": "First Party",
    "category": "Whip Operations",
    "critical": false,
    "active": true,
    "checkText": "Vendor and appraisal assignments made and followed up",
    "passingStandard": "Assigned and chased where open",
    "whereToFind": "Claim tasks",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-11",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "First party team's liability decision reviewed and either confirmed or corrected",
    "passingStandard": "Review documented, not assumed",
    "whereToFind": "Notes / Liability Assignment",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LPD-12",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Liability decision makes sense against the facts of loss and all evidence in the file",
    "passingStandard": "Decision supported by the evidence, with the basis stated",
    "whereToFind": "Notes / Liability Assignment",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LPD-13",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Correct comparative or contributory standard applied for the state",
    "passingStandard": "Correct standard named and applied",
    "whereToFind": "Notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LPD-14",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Coverage decision reviewed, and any fact that would change the standing position identified and escalated",
    "passingStandard": "Reviewed; anything contrary escalated",
    "whereToFind": "Coverage Check / notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LPD-15",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Conflicting evidence addressed rather than ignored",
    "passingStandard": "Conflicts named and reconciled",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-16",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Where evidence needed to resolve the exposure was missing, it was pursued rather than the decision made without it",
    "passingStandard": "Outreach made, or a documented reason the decision can stand without it",
    "whereToFind": "Notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LPD-17",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Reserve reasonable against the evaluated exposure",
    "passingStandard": "Within tolerance of the documented evaluation",
    "whereToFind": "Reserves / notes",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "LPD-35",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Claimant damages verified before payment: estimate, photographs, ownership and prior damage",
    "passingStandard": "All four verified",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LPD-36",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Subrogation pursued where liability is adverse to the other party, or the reason not to is documented",
    "passingStandard": "Pursued or documented",
    "whereToFind": "Recovery fields / notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LPD-37",
    "role": "Liability - PD",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Arbitration considered where the other carrier is a signatory",
    "passingStandard": "Considered and documented",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-01",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Reserve set on every open exposure within 7 days of assignment",
    "passingStandard": "Reserve present within 7 days of the exposure moving to open in the handler's name",
    "whereToFind": "Exposure > reserves state, assignment date",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-02",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "No exposure left in draft longer than 14 days",
    "passingStandard": "Opened with a reserve, or closed, within 14 days",
    "whereToFind": "Exposure status history",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-03",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Where a draft exposure was closed, the reason is documented",
    "passingStandard": "Closed for insufficient information or no legal liability, and the note says which",
    "whereToFind": "Notes / exposure record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-04",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Coverage status confirmed and completed in the system",
    "passingStandard": "Completed, not left open on an assumption",
    "whereToFind": "Claim Details > Coverage Check",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-05",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Liability assignment fields completed and consistent with the liability note",
    "passingStandard": "Fields and note agree",
    "whereToFind": "Claim Details > Liability Assignment",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-06",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Photographs and any dashcam or telematics footage from our vehicle are in the file, or were requested with the attempt documented",
    "passingStandard": "In file, or requested and documented",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LPD-07",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "All other available evidence secured: claimant photographs and estimate, scene photographs, police report, witness information and TNC trip data",
    "passingStandard": "Each obtained, or documented as unavailable with the attempt",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LPD-08",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Payments recorded against the correct exposure and payee",
    "passingStandard": "Matches the exposure and the party paid",
    "whereToFind": "Financial tab",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-09",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Documents filed to the correct claim and categorized",
    "passingStandard": "Correct claim, correct category",
    "whereToFind": "Documents tab",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-10",
    "role": "Liability - PD",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Tags updated to reflect current liability, subrogation and injury status",
    "passingStandard": "Tags match the file",
    "whereToFind": "Claim header tags",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-23",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Liability note in the file",
    "passingStandard": "Present, stating the position and the basis for it",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-24",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "A note exists for every touch of the claim",
    "passingStandard": "Every call, email and action recorded on the day it happened",
    "whereToFind": "Notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LPD-25",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Emails to and from any party are in the file",
    "passingStandard": "Correspondence filed, not summarized only",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-26",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Coverage change documented when made",
    "passingStandard": "Change and reason both noted",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-27",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Reserve change documented with the reason",
    "passingStandard": "Change and reason both noted",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-28",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Payment documented when issued",
    "passingStandard": "Amount, payee, exposure and date noted",
    "whereToFind": "Notes / Financial",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LPD-29",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Latest note states current status and the next step",
    "passingStandard": "Specific next step with a date",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-30",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "File is defensible: a reader can see why each decision was made",
    "passingStandard": "Reasoning present for each material decision",
    "whereToFind": "Notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LPD-38",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Negotiation documented, including each demand and each offer",
    "passingStandard": "Full sequence present with dates",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-39",
    "role": "Liability - PD",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Release correct for the state and the party, sent and received dates both documented, executed before payment",
    "passingStandard": "Correct form, both dates noted, executed first",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule + human"
  },
  {
    "itemKey": "LPD-18",
    "role": "Liability - PD",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Outbound contact made to whoever holds the missing evidence, whether claimant, member, attorney or carrier",
    "passingStandard": "Contact attempted with the right party",
    "whereToFind": "Notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LPD-19",
    "role": "Liability - PD",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Contact attempts documented with date, method and outcome",
    "passingStandard": "All three present for each attempt",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-20",
    "role": "Liability - PD",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Follow-up made where requested evidence was not produced",
    "passingStandard": "Chased rather than left open",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LPD-21",
    "role": "Liability - PD",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "No unexplained gap in file movement",
    "passingStandard": "No gap beyond the standard between substantive actions",
    "whereToFind": "Note dates",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LPD-22",
    "role": "Liability - PD",
    "category": "Communication & Follow-Up",
    "critical": true,
    "active": true,
    "checkText": "No admission and no unauthorized disclosure of limits",
    "passingStandard": "None present",
    "whereToFind": "Notes / correspondence",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LPD-40",
    "role": "Liability - PD",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Correspondence used the current template, correct state and correct entity naming",
    "passingStandard": "Correct on all three",
    "whereToFind": "Documents",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LPD-31",
    "role": "Liability - PD",
    "category": "Whip Operations",
    "critical": true,
    "active": true,
    "checkText": "Authority granted at Thursday's liability authorization meeting documented in the claim by end of day Thursday",
    "passingStandard": "Authority, amount and date in the file by close of business Thursday",
    "whereToFind": "Notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LPD-32",
    "role": "Liability - PD",
    "category": "Whip Operations",
    "critical": true,
    "active": true,
    "checkText": "No offer or payment made beyond the authority documented in the file",
    "passingStandard": "Offer or payment at or under the granted authority",
    "whereToFind": "Notes / Financial",
    "gradingMethod": "Rule + human"
  },
  {
    "itemKey": "LPD-33",
    "role": "Liability - PD",
    "category": "Whip Operations",
    "critical": false,
    "active": true,
    "checkText": "Board and Slack updated where the process requires it",
    "passingStandard": "Updated",
    "whereToFind": "Board / Slack",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "LPD-34",
    "role": "Liability - PD",
    "category": "Whip Operations",
    "critical": true,
    "active": true,
    "checkText": "Escalation made where required, including suit, subpoena, regulatory notice and policy-limit demands",
    "passingStandard": "Escalated within the business day",
    "whereToFind": "Notes / routing record",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-11",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "First party team's liability decision reviewed and either confirmed or corrected",
    "passingStandard": "Review documented, not assumed",
    "whereToFind": "Notes / Liability Assignment",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LINJ-12",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Liability decision makes sense against the facts of loss and all evidence in the file",
    "passingStandard": "Decision supported by the evidence, with the basis stated",
    "whereToFind": "Notes / Liability Assignment",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LINJ-13",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Correct comparative or contributory standard applied for the state",
    "passingStandard": "Correct standard named and applied",
    "whereToFind": "Notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LINJ-14",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Coverage decision reviewed, and any fact that would change the standing position identified and escalated",
    "passingStandard": "Reviewed; anything contrary escalated",
    "whereToFind": "Coverage Check / notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LINJ-15",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Conflicting evidence addressed rather than ignored",
    "passingStandard": "Conflicts named and reconciled",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-16",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Where evidence needed to resolve the exposure was missing, it was pursued rather than the decision made without it",
    "passingStandard": "Outreach made, or a documented reason the decision can stand without it",
    "whereToFind": "Notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LINJ-17",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Reserve reasonable against the evaluated exposure",
    "passingStandard": "Within tolerance of the documented evaluation",
    "whereToFind": "Reserves / notes",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "LINJ-37",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Medical records and bills requested, received and reviewed",
    "passingStandard": "Requested within standard; review documented",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-38",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Treatment gaps, causation and mechanism of injury assessed against the physical damage",
    "passingStandard": "Assessment documented",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-39",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": false,
    "active": true,
    "checkText": "Prior and subsequent claims, and any liens, identified and addressed",
    "passingStandard": "Identified, or documented as none",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-40",
    "role": "Liability - Injury",
    "category": "Decision Quality & Accuracy",
    "critical": true,
    "active": true,
    "checkText": "Evaluation documented with specials, general damages rationale, venue and liability discount",
    "passingStandard": "All four present",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-01",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Reserve set on every open exposure within 7 days of assignment",
    "passingStandard": "Reserve present within 7 days of the exposure moving to open in the handler's name",
    "whereToFind": "Exposure > reserves state, assignment date",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-02",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "No exposure left in draft longer than 14 days",
    "passingStandard": "Opened with a reserve, or closed, within 14 days",
    "whereToFind": "Exposure status history",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-03",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Where a draft exposure was closed, the reason is documented",
    "passingStandard": "Closed for insufficient information or no legal liability, and the note says which",
    "whereToFind": "Notes / exposure record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-04",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Coverage status confirmed and completed in the system",
    "passingStandard": "Completed, not left open on an assumption",
    "whereToFind": "Claim Details > Coverage Check",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-05",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Liability assignment fields completed and consistent with the liability note",
    "passingStandard": "Fields and note agree",
    "whereToFind": "Claim Details > Liability Assignment",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-06",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Photographs and any dashcam or telematics footage from our vehicle are in the file, or were requested with the attempt documented",
    "passingStandard": "In file, or requested and documented",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-07",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "All other available evidence secured: claimant photographs and estimate, scene photographs, police report, witness information and TNC trip data",
    "passingStandard": "Each obtained, or documented as unavailable with the attempt",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-08",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Payments recorded against the correct exposure and payee",
    "passingStandard": "Matches the exposure and the party paid",
    "whereToFind": "Financial tab",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-09",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Documents filed to the correct claim and categorized",
    "passingStandard": "Correct claim, correct category",
    "whereToFind": "Documents tab",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-10",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": false,
    "active": true,
    "checkText": "Tags updated to reflect current liability, subrogation and injury status",
    "passingStandard": "Tags match the file",
    "whereToFind": "Claim header tags",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-35",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "PIP or MedPay handled within the statutory timeframe for the state",
    "passingStandard": "Within statute",
    "whereToFind": "Dates / notes",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-36",
    "role": "Liability - Injury",
    "category": "Data & File Integrity",
    "critical": true,
    "active": true,
    "checkText": "Statutory deadlines tracked, including limitations and state notice requirements",
    "passingStandard": "Tracked with dates in diary",
    "whereToFind": "Diary",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-23",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Liability note in the file",
    "passingStandard": "Present, stating the position and the basis for it",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-24",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "A note exists for every touch of the claim",
    "passingStandard": "Every call, email and action recorded on the day it happened",
    "whereToFind": "Notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-25",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Emails to and from any party are in the file",
    "passingStandard": "Correspondence filed, not summarized only",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-26",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Coverage change documented when made",
    "passingStandard": "Change and reason both noted",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-27",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Reserve change documented with the reason",
    "passingStandard": "Change and reason both noted",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-28",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Payment documented when issued",
    "passingStandard": "Amount, payee, exposure and date noted",
    "whereToFind": "Notes / Financial",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-29",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": false,
    "active": true,
    "checkText": "Latest note states current status and the next step",
    "passingStandard": "Specific next step with a date",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-30",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "File is defensible: a reader can see why each decision was made",
    "passingStandard": "Reasoning present for each material decision",
    "whereToFind": "Notes",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LINJ-42",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Negotiation plan documented before the first offer",
    "passingStandard": "Plan present, with the target and walk-away position",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-43",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Initial offer documented with date and amount",
    "passingStandard": "Both present",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-44",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Each counter and the final offer documented",
    "passingStandard": "Full sequence with dates",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-45",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Information learned after the initial offer that could change the evaluation is documented",
    "passingStandard": "New facts recorded and the effect on value stated",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-46",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Release sent date and release received date both documented",
    "passingStandard": "Both dates in the file",
    "whereToFind": "Notes / documents",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-47",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Settlement documents correct for the state and the claimant's status, including minors, estates and represented parties",
    "passingStandard": "Correct form used",
    "whereToFind": "Documents",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "LINJ-48",
    "role": "Liability - Injury",
    "category": "Claim Life Clarity",
    "critical": true,
    "active": true,
    "checkText": "Liens resolved or protected before disbursement",
    "passingStandard": "Resolved or protected, documented",
    "whereToFind": "Documents / notes",
    "gradingMethod": "Rule + human"
  },
  {
    "itemKey": "LINJ-18",
    "role": "Liability - Injury",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Outbound contact made to whoever holds the missing evidence, whether claimant, member, attorney or carrier",
    "passingStandard": "Contact attempted with the right party",
    "whereToFind": "Notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-19",
    "role": "Liability - Injury",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Contact attempts documented with date, method and outcome",
    "passingStandard": "All three present for each attempt",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-20",
    "role": "Liability - Injury",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Follow-up made where requested evidence was not produced",
    "passingStandard": "Chased rather than left open",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "LINJ-21",
    "role": "Liability - Injury",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "No unexplained gap in file movement",
    "passingStandard": "No gap beyond the standard between substantive actions",
    "whereToFind": "Note dates",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-22",
    "role": "Liability - Injury",
    "category": "Communication & Follow-Up",
    "critical": true,
    "active": true,
    "checkText": "No admission and no unauthorized disclosure of limits",
    "passingStandard": "None present",
    "whereToFind": "Notes / correspondence",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "LINJ-41",
    "role": "Liability - Injury",
    "category": "Communication & Follow-Up",
    "critical": true,
    "active": true,
    "checkText": "Demand acknowledged within standard, and the response issued within the stated deadline or an extension documented",
    "passingStandard": "Both met, or extension documented",
    "whereToFind": "Dates / notes",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "LINJ-49",
    "role": "Liability - Injury",
    "category": "Communication & Follow-Up",
    "critical": false,
    "active": true,
    "checkText": "Correspondence used the current template, correct state and correct entity naming",
    "passingStandard": "Correct on all three",
    "whereToFind": "Documents",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-31",
    "role": "Liability - Injury",
    "category": "Whip Operations",
    "critical": true,
    "active": true,
    "checkText": "Authority granted at Thursday's liability authorization meeting documented in the claim by end of day Thursday",
    "passingStandard": "Authority, amount and date in the file by close of business Thursday",
    "whereToFind": "Notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "LINJ-32",
    "role": "Liability - Injury",
    "category": "Whip Operations",
    "critical": true,
    "active": true,
    "checkText": "No offer or payment made beyond the authority documented in the file",
    "passingStandard": "Offer or payment at or under the granted authority",
    "whereToFind": "Notes / Financial",
    "gradingMethod": "Rule + human"
  },
  {
    "itemKey": "LINJ-33",
    "role": "Liability - Injury",
    "category": "Whip Operations",
    "critical": false,
    "active": true,
    "checkText": "Board and Slack updated where the process requires it",
    "passingStandard": "Updated",
    "whereToFind": "Board / Slack",
    "gradingMethod": "Human"
  },
  {
    "itemKey": "LINJ-34",
    "role": "Liability - Injury",
    "category": "Whip Operations",
    "critical": true,
    "active": true,
    "checkText": "Escalation made where required, including suit, subpoena, regulatory notice and policy-limit demands",
    "passingStandard": "Escalated within the business day",
    "whereToFind": "Notes / routing record",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "INT-01",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": true,
    "active": true,
    "checkText": "Correct trigger identified for the report: in-office photo trigger or remote-market business-hour trigger",
    "passingStandard": "Trigger named and matches the evidence in the thread",
    "whereToFind": "#claims / #claims-remotemarkets post",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-02",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": true,
    "active": true,
    "checkText": "In office: recorded statement attempted within 10 minutes",
    "passingStandard": "Measured from the photo-bearing intake post, or the first photo-bearing thread reply where in-store staff added them later",
    "whereToFind": "Slack post timestamp vs attempt record",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-03",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": true,
    "active": true,
    "checkText": "Remote market: recorded statement completed within 4 business hours",
    "passingStandard": "Markets other than GA, MD and IL. Clock starts on arrival Mon-Fri 09:00-18:00, otherwise 09:00 the next business day",
    "whereToFind": "Slack post timestamp vs statement completion",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-04",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": false,
    "active": true,
    "checkText": "Business hours only applied to the remote clock",
    "passingStandard": "Overnight and weekend time not counted against the representative",
    "whereToFind": "Timing calculation",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-05",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": false,
    "active": true,
    "checkText": "Where the statement was completed before photos were later uploaded, the sequence is treated as complete rather than late",
    "passingStandard": "No duplicate 10-minute attempt expected or scored",
    "whereToFind": "Statement time vs photo time",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-06",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": false,
    "active": true,
    "checkText": "Report acknowledged and an accountable owner assigned, with the assignment time visible",
    "passingStandard": "Owner and timestamp both recorded",
    "whereToFind": "Slack thread / intake record",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-07",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": false,
    "active": true,
    "checkText": "Attempt cadence appropriate and documented after no answer",
    "passingStandard": "Follow-up attempts timely and recorded",
    "whereToFind": "Notes / intake record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-08",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": false,
    "active": true,
    "checkText": "No aging report left without a documented next step",
    "passingStandard": "Next step present on anything still open",
    "whereToFind": "Intake record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-09",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": true,
    "active": true,
    "checkText": "Urgent reports escalated: injury, tow or storage risk, safety concern, stated deadline",
    "passingStandard": "Escalated and routed",
    "whereToFind": "Slack thread / notes",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "INT-10",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": false,
    "active": true,
    "checkText": "Possible duplicate across #claims and #claims-remotemarkets flagged for review rather than worked as a second intake",
    "passingStandard": "Flagged, not merged and not discarded",
    "whereToFind": "Intake record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-11",
    "role": "Intake",
    "category": "Timeliness and ownership",
    "critical": false,
    "active": true,
    "checkText": "A post concerning an already-open claim handled as follow-up rather than logged as a new intake",
    "passingStandard": "Linked to the existing claim, not double-counted",
    "whereToFind": "Intake record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-12",
    "role": "Intake",
    "category": "Member engagement",
    "critical": false,
    "active": true,
    "checkText": "First attempt placed by the assigned owner and documented with time, method and outcome",
    "passingStandard": "All three recorded",
    "whereToFind": "Notes / intake record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-13",
    "role": "Intake",
    "category": "Member engagement",
    "critical": false,
    "active": true,
    "checkText": "Callback details captured in full",
    "passingStandard": "Name, phone, email and relationship to the member",
    "whereToFind": "Intake fields",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-14",
    "role": "Intake",
    "category": "Member engagement",
    "critical": false,
    "active": true,
    "checkText": "Communication clear, professional and appropriate to the situation",
    "passingStandard": "No unprofessional exchange",
    "whereToFind": "Recording",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "INT-15",
    "role": "Intake",
    "category": "Member engagement",
    "critical": false,
    "active": true,
    "checkText": "A clear next step given to the member and recorded",
    "passingStandard": "Stated on the call and in the note",
    "whereToFind": "Recording / notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-16",
    "role": "Intake",
    "category": "Member engagement",
    "critical": false,
    "active": true,
    "checkText": "Follow-up attempts made where the member did not answer",
    "passingStandard": "Attempts made; a no-answer alone is not a defect",
    "whereToFind": "Notes",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-17",
    "role": "Intake",
    "category": "Member engagement",
    "critical": false,
    "active": true,
    "checkText": "Promised follow-up honored within the timeframe given",
    "passingStandard": "On or before the time promised",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-18",
    "role": "Intake",
    "category": "Member engagement",
    "critical": true,
    "active": true,
    "checkText": "No coverage or liability position stated to the member or claimant",
    "passingStandard": "None stated",
    "whereToFind": "Recording",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "INT-19",
    "role": "Intake",
    "category": "Recorded-statement capture",
    "critical": true,
    "active": true,
    "checkText": "Permission to record captured on the recording",
    "passingStandard": "Present at the start",
    "whereToFind": "Recording",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-20",
    "role": "Intake",
    "category": "Recorded-statement capture",
    "critical": true,
    "active": true,
    "checkText": "Material facts captured from the statement",
    "passingStandard": "Who, what, when, where, vehicles and drivers, injuries and damages, claim identifiers, witnesses and urgency",
    "whereToFind": "Recording / transcript",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-21",
    "role": "Intake",
    "category": "Recorded-statement capture",
    "critical": false,
    "active": true,
    "checkText": "Facts of loss taken in usable sequence",
    "passingStandard": "Location, sequence of events, impact, other party, injuries, damages, police and witness information",
    "whereToFind": "Recording / transcript",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-22",
    "role": "Intake",
    "category": "Recorded-statement capture",
    "critical": true,
    "active": true,
    "checkText": "Statement taken cleanly, with no leading or argumentative questioning",
    "passingStandard": "None present",
    "whereToFind": "Recording",
    "gradingMethod": "Claude + human"
  },
  {
    "itemKey": "INT-23",
    "role": "Intake",
    "category": "Recorded-statement capture",
    "critical": false,
    "active": true,
    "checkText": "Voicemail retained where the member could not complete the statement",
    "passingStandard": "Voicemail on file",
    "whereToFind": "Documents",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-24",
    "role": "Intake",
    "category": "Recorded-statement capture",
    "critical": true,
    "active": true,
    "checkText": "Recording or voicemail attached to the claim and to the correct exposure",
    "passingStandard": "Attached correctly",
    "whereToFind": "Documents / exposure record",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-25",
    "role": "Intake",
    "category": "Intake notes and field completion",
    "critical": false,
    "active": true,
    "checkText": "Intake note accurate and usable by the next handler",
    "passingStandard": "Handler can act without going back to the source",
    "whereToFind": "Intake note",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-26",
    "role": "Intake",
    "category": "Intake notes and field completion",
    "critical": false,
    "active": true,
    "checkText": "Required structured loss fields complete",
    "passingStandard": "All required fields populated",
    "whereToFind": "Intake fields",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-27",
    "role": "Intake",
    "category": "Intake notes and field completion",
    "critical": true,
    "active": true,
    "checkText": "No material conflict between the statement, the note and the entered data",
    "passingStandard": "Sources agree, or the difference is explained",
    "whereToFind": "Recording vs note vs fields",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-28",
    "role": "Intake",
    "category": "Intake notes and field completion",
    "critical": false,
    "active": true,
    "checkText": "Missing information flagged with the reason rather than left blank",
    "passingStandard": "Flag present and explains why",
    "whereToFind": "Intake fields / note",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-29",
    "role": "Intake",
    "category": "Intake notes and field completion",
    "critical": false,
    "active": true,
    "checkText": "Identity and callback details in the note match the structured fields",
    "passingStandard": "Match, or the conflict is flagged",
    "whereToFind": "Note vs fields",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "INT-30",
    "role": "Intake",
    "category": "Intake notes and field completion",
    "critical": false,
    "active": true,
    "checkText": "Every usable identifier captured, or the reason it was unavailable documented",
    "passingStandard": "Claim number, member or policy identifier, vehicle and VIN, date of loss",
    "whereToFind": "Intake fields",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "INT-31",
    "role": "Intake",
    "category": "Intake notes and field completion",
    "critical": false,
    "active": true,
    "checkText": "Urgency and commitments recorded and routed appropriately",
    "passingStandard": "Priority and next action both recorded",
    "whereToFind": "Intake record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-32",
    "role": "Intake",
    "category": "Intake notes and field completion",
    "critical": false,
    "active": true,
    "checkText": "Disposition recorded: what was promised, transferred, opened or requested",
    "passingStandard": "Status and next step reflect the commitment",
    "whereToFind": "Intake record",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-33",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": true,
    "active": true,
    "checkText": "Correct SnapSheet claim identified and linked to the intake",
    "passingStandard": "Linked to the right claim",
    "whereToFind": "Claim linkage",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-34",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": false,
    "active": true,
    "checkText": "Claimant and member data match the confirmed intake facts",
    "passingStandard": "Names, contact details, vehicles and identifiers all match",
    "whereToFind": "Claim Details",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "INT-35",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": false,
    "active": true,
    "checkText": "Loss data recorded consistently with the intake",
    "passingStandard": "Date, location, facts of loss, parties, vehicles, injuries and damages",
    "whereToFind": "Claim Details > Facts of Loss / Incident Details",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "INT-36",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": false,
    "active": true,
    "checkText": "Usable intake note or statement summary present in SnapSheet with next steps",
    "passingStandard": "Present and usable",
    "whereToFind": "Notes",
    "gradingMethod": "Claude"
  },
  {
    "itemKey": "INT-37",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": false,
    "active": true,
    "checkText": "Claim status appropriate, with pending contacts, documents and escalations visible to the next team member",
    "passingStandard": "Status correct and pending items visible",
    "whereToFind": "Claim status / tasks",
    "gradingMethod": "Rule + Claude"
  },
  {
    "itemKey": "INT-38",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": true,
    "active": true,
    "checkText": "New exposure opened for every damaged vehicle and every reported injury, with the correct exposure type",
    "passingStandard": "One per vehicle and per injured party; Vehicle, PipMedPay, InjuredPerson, Property or Other as the facts require",
    "whereToFind": "Auto Damage / Injured Person Exposures",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-39",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": false,
    "active": true,
    "checkText": "Exposures named correctly",
    "passingStandard": "Vehicles by year, make, model and VIN; injured parties by name",
    "whereToFind": "Exposure record",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-40",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": true,
    "active": true,
    "checkText": "Uber or Lyft inquiry filed where a gig period is involved",
    "passingStandard": "Inquiry submitted on the day the claim is worked",
    "whereToFind": "TNC inquiry log / notes",
    "gradingMethod": "Rule"
  },
  {
    "itemKey": "INT-41",
    "role": "Intake",
    "category": "SnapSheet completion and consistency",
    "critical": false,
    "active": true,
    "checkText": "Tags and notes updated with the gig period and the TNC inquiry result",
    "passingStandard": "Both recorded once known",
    "whereToFind": "Claim header tags / notes",
    "gradingMethod": "Rule"
  }
];
